// export const SELECCIONAR_CLIENTE = "SELECCIONAR_CLIENTE"
// export const SELECCIONAR_PRODUCTO = "SELECCIONAR_PRODUCTO"
// export const CANTIDAD_PRODUCTOS = "CANTIDAD_PRODUCTOS"

const types = {
    SELECCIONAR_CLIENTE: "SELECCIONAR_CLIENTE",
    SELECCIONAR_PRODUCTO: "SELECCIONAR_PRODUCTO",
    CANTIDAD_PRODUCTOS: "CANTIDAD_PRODUCTOS",
    ACTUALIZAR_TOTAL: "ACTUALIZAR_TOTAL",
}

export default  types 